### ISSUE TITLE
Starting issues

### ISSUE THREAD

**Issue by ghost** [remorses/mongoke-examples#1]
Hi,

having the system:

- Up and running MongoDB via Docker on `http://localhost:32774`
- Created a database `up2`

My `docker-compose.yml`:

```
version: "3"

services:
  mongoke:
    ports:
      - 8090:80
    image: mongoke/mongoke:latest
    environment:
      - DB_URL=mongodb://localhost:32774/up2
    volumes:
      - ./mongoke.yml:/conf.yml
      # - ./domain.skema:/domain.skema
  populate-db:
    image: mongoke/populate-mongo
    volumes:
      - ./mongoke.yml/:/conf.yml
    environment:
      - DB_URL=mongodb://0.0.0.0:32774/up2
  #mongo:
  #    image: mongo
  #    logging:
  #        driver: none
```

Trying to `docker-compose up` in the basic project results in the following issue:

```
➜  basic git:(master) ✗ docker-compose up
Creating basic_mongoke_1     ... done
Creating basic_populate-db_1 ... done
Attaching to basic_populate-db_1, basic_mongoke_1
populate-db_1  | object_ids_pool ['User', 'BlogPost']
populate-db_1  | generating object ids between User and {'BlogPost'}, from a pool of 20
populate-db_1  | persisting 20 documents in users in db up2
mongoke_1      | INFO: Started server process [8]
mongoke_1      | INFO: Waiting for application startup.
mongoke_1      | INFO: Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)

populate-db_1  | Traceback (most recent call last):
populate-db_1  |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
populate-db_1  |     "__main__", mod_spec)
populate-db_1  |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
populate-db_1  |     exec(code, run_globals)
populate-db_1  |   File "/src/__main__.py", line 97, in <module>
populate-db_1  |     asyncio.run(main(yaml.safe_load(open(CONF_PATH)), url=DB_URL))
populate-db_1  |   File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
populate-db_1  |     return loop.run_until_complete(main)
populate-db_1  |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
populate-db_1  |     return future.result()
populate-db_1  |   File "/src/__main__.py", line 90, in main
populate-db_1  |     await collection.insert_many(items)
populate-db_1  |   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
populate-db_1  |     result = self.fn(*self.args, **self.kwargs)
populate-db_1  |   File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 758, in insert_many
populate-db_1  |     blk.execute(write_concern, session=session)
populate-db_1  |   File "/usr/local/lib/python3.7/site-packages/pymongo/bulk.py", line 511, in execute
populate-db_1  |     return self.execute_command(generator, write_concern, session)
populate-db_1  |   File "/usr/local/lib/python3.7/site-packages/pymongo/bulk.py", line 344, in execute_command
populate-db_1  |     with client._tmp_session(session) as s:
populate-db_1  |   File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
populate-db_1  |     return next(self.gen)
populate-db_1  |   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1820, in _tmp_session
populate-db_1  |     s = self._ensure_session(session)
populate-db_1  |   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
populate-db_1  |     return self.__start_session(True, causal_consistency=False)
populate-db_1  |   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
populate-db_1  |     server_session = self._get_server_session()
populate-db_1  |   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
populate-db_1  |     return self._topology.get_server_session()
populate-db_1  |   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
populate-db_1  |     None)
populate-db_1  |   File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
populate-db_1  |     self._error_message(selector))
populate-db_1  | pymongo.errors.ServerSelectionTimeoutError: localhost:32774: [Errno 111] Connection refused
basic_populate-db_1 exited with code 1
```

I can see graphiql on http://localhost:8090/, but when i query the database with the given standard query:

```
{
  Store {
    url
    products(last: 3, cursorField: title) {
      nodes {
        _id
        title
        tags {
          code
        }
      }
      pageInfo {
        endCursor
      }
    }
    seller {
      _id
      email
    }
  }
}
```

it responses with:

```
{
  "data": {
    "Store": null
  },
  "errors": [
    {
      "message": "localhost:32774: [Errno 111] Connection refused",
      "path": [
        "Store"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

Any suggestions?

**Comment by ghost** [comment]
Maybe i should insert a `config.yml` in the basic example folder, but there's no example how to do it the right way. My predefined config look like:

```
Configuration:
    schema?: up2
    schema_url?: mongodb://localhost:32774/up2
    schema_path?: up2
    types:
        User:
            collection: users
            exposed?: true
            pipeline?: [Any]
            disambiguations?:
                ...: Str
            guards?: [
                expression: Str
                excluded?: [Str]
                when?: "after" | "before"
            ]
        BlogPost:
            collection: posts
            exposed?: true
            pipeline?: [Any]
            disambiguations?:
                ...: Str
                guards?: [
                    expression: Str
                    excluded?: [Str]
                    when?: "after" | "before"
                ]
    relations?: [
        from: User
          to: BlogPost
          relation_type: to_many
          where:
            author_id: ${{ parent['_id'] }}
    ]
    #jwt?:
    #    secret?: Str
    #    header_name?: Str # default is "Authorization"
    #    header_scheme?: Str # default is "Bearer"
    #    required?: Bool
    #    algorithms?: ["H256" | "HS512" | "HS384" | "RS256" | "RS384" | "RS512" | "ES256" | "ES384" | "ES521" | "ES512" | "PS256" | "PS384" | "PS512"]

Url: http://localhost:8090/
```

Maybe there's a development ready example file?!
